server:
  port: 8222


jwt:
  secret: ihzu3h4i
  expiration: 86400000
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "GET, POST, PUT, DELETE"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
            
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**