export enum ECategory {
    STARTERS = 'STARTERS',
    PASTAS = 'PASTAS',
    PIZZAS = 'PIZZAS',
    BURGERS = 'BURGERS',
    DESSERTS = 'DESSERTS',
    SALADS = 'SALADS',
    GRILLED_MEATS = 'GRILLED_MEATS',
    SEAFOODS = 'SEAFOODS',
    CHICKEN = 'CHICKEN',
    VEGETARIAN = 'VEGETARIAN',
    COLD_DRINKS = 'COLD_DRINKS',
    HOT_DRINKS = 'HOT_DRINKS',
}